services:
  - type: web
    name: secret-santa
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: bash start.sh
